# Generated by Django 2.2.18 on 2021-04-08 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLib',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lib_goods_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.GoodsInfo')),
                ('lib_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Myuser')),
            ],
        ),
    ]
