# Generated by Django 2.2.18 on 2021-04-11 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField(default=0)),
                ('item_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cate_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Category')),
                ('item_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.ItemInfo')),
            ],
        ),
    ]
