# Generated by Django 2.2.18 on 2021-04-08 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.IntegerField(default=-1)),
                ('lib_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Myuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_book_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.GoodsInfo')),
                ('order_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.MyOrder')),
            ],
        ),
        migrations.AddField(
            model_name='myorder',
            name='order_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus'),
        ),
    ]
