# Generated by Django 2.2.18 on 2021-04-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='order_status',
        ),
    ]
