# Generated by Django 2.2.18 on 2021-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_myorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='order_status',
            field=models.CharField(default='Waiting for payment', max_length=30),
        ),
    ]
