# Generated by Django 2.2.18 on 2021-04-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_myorder_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
