# Generated by Django 2.2.18 on 2021-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210410_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
